export default {
  // Gluee
  'Deletee (Intro)': { a: 'B, T', id: 'sZYB5fFCiA4', d: 209 },
  Safehouse: { a: 'B', id: 'DJCjNBYwoNo', d: 163 },
  Ebay: { a: 'B, T, E', id: 'Nnwmc3k58Rw', d: 225 },
  Shadowface: { a: 'B, Bones', id: 'SlP5ILjf0UY', d: 215 },
  Spellbound: { a: 'B', id: 'Kp76OH12jcY', d: 205 },
  'Everlasting Flames': { a: 'B, T', id: 'fv_0cgtA3OM', d: 201 },
  Freeze: { a: 'B', id: 'fuC1jKU-wCw', d: 176 },
  'Upgrade Enabled': { a: 'B', id: 'YmaMerfPJng', d: 177 },
  Unreal: { a: 'B', id: 'QyX9Nymmtx0', d: 133 },

  Dragonfly: { a: 'B', id: 'TrRpnycSQoA', d: 143 },
  'Blood Rain': { a: 'B, Y', id: 'RFcTac1ZUxY', d: 199 },
  'Into Dust': { a: 'B', id: 'TZnIoa4zNuw', d: 140 },
  // Eversince
  'Who Goes There': { a: 'B', id: '7gfItwH3LKQ', d: 189 },
  'So What': { a: 'B, E', id: 'miMP5SQ_JQA', d: 199 },
  Lovenote: { a: 'B', id: 'zCn_8eJ8x6M', d: 186 },
  'Missing Person': { a: 'B', id: 'pQ2TmnjNCNg', d: 200 },
  Romeo: { a: 'B', id: 'SzdoeUCM2HU', d: 171 },
  'Xd Out': { a: 'B', id: 'WH6o7diTHSs', d: 217 },
  Sick: { a: 'B', id: 'zN8I_ziciHw', d: 180 },
  Rip: { a: 'B', id: '8ww_eYCuIS8', d: 175 },
  'Bloodveil/Stillborn': { a: 'B, E', id: 'JN6sfZJZYsk', d: 210 },
  Sugar: { a: 'B', id: 'OqzBxiiR2QE', d: 186 },
  'Wrist Cry': { a: 'B', id: 'Ug3g3F9gwGM', d: 235 },
  Skin: { a: 'B', id: 'hOP_x9JK1-g', d: 216 },
  // RIP Bladee
  '7-Eleven': { a: 'B', id: 'ftUB2JvEImM', d: 164 },
  Butterfly: { a: 'B, T', id: '62tXF_7D0fs', d: 191 },
  MJ: { a: 'B, Y', id: '30dSFD6vqds', d: 245 },
  Psycho: { a: 'B, Adamn Killa', id: '18BeHal8hTs', d: 207 },
  '50SACINMYSOCIDGAF': { a: 'B, Y', id: 'C1L4KXgBAyo', d: 210 },
  'Destroy Me': { a: 'B', id: 'ithDuu8A680', d: 168 },
  // E
  'AAA Powerline': { a: 'E', id: 'HeLdS491PDo', d: 256 },
  Peroxide: { a: 'E', id: 'toVvEuNRo3Y', d: 214 },
  Fragile: { a: 'E', id: 'fP7GD3F1euw', d: 173 },
  'Fruit Bleed Juice': { a: 'E', id: 'VBFJDYX8SPY', d: 72 },
  Cc: { a: 'E', id: 'hQNkd7pP_6A', d: 154 },
  Calcium: { a: 'E', id: '5XJLdu5qAhM', d: 224 },
  'Sugar & Diesel': { a: 'E', id: '4kswlS7SRsM', d: 199 },
  "Don't Ask": { a: 'E', id: 'rUoqWE429pg', d: 140 },
  Security: { a: 'E', id: 'Hv6kNL9vjj0', d: 155 },
  'Blue Eyes': { a: 'E', id: 'AbVrh0hUuQM', d: 93 },
  Time: { a: 'E', id: 'rKsb71ALRvo', d: 121 },

  'Legendary Member': { a: 'T, B, E, Y', id: 'WGr2QOy0ps8', d: 156 },
  // Icedancer
  SmartWater: { a: 'B', id: '4m0sVGVTTes', d: 150 },
  OKK: { a: 'B', id: 'D9QRWeiDxKI', d: 93 },
  'Mallwhore Freeestyle': { a: 'B', id: '8QUT4hpQbsw', d: 119 },
  'Be Nice 2 Me': { a: 'B', id: 'hJQjWKq7vrc', d: 127 },
  'Frosty the Snowman': { a: 'B', id: 'VOmLLsv2dDI', d: 170 },
  'Inside Out': { a: 'B, Y', id: 'ULUZ6dSHwbo', d: 137 },
  Close: { a: 'B', id: 'PCxgFp1H0Lk', d: 202 },
  Jaws: { a: 'B', id: 'kHbyCF35QNs', d: 116 },
  "Cartier'God Icedancer (Intermission)": { a: 'B', id: 'yGqgSa0y-dM', d: 181 },
  'Side by Side': { a: 'B, T', id: 'oF8r39I6vdA', d: 136 },
  Topman: { a: 'B', id: 'zeleydIQeM0', d: 193 },
  Waster: { a: 'B', id: 'CMrcYUxBAxc', d: 121 },
  'Special Place': { a: 'B', id: 'kuiB3xSaH8k', d: 122 },
  'Dg Jeans': { a: 'B', id: 'ONrNAX6j3vc', d: 103 },
  'Feel Like': { a: 'B', id: 'uDUCBwD7Hgs', d: 94 },
  Linkdin: { a: 'B', id: 'bnD2CWhspEM', d: 153 },
  'For Nothing': { a: 'B', id: '_eztqePWUwY', d: 120 },
  Anything: { a: 'B', id: 'pN72OsNCKNA', d: 157 },
  'The Silent Boy Cries (Ripsquadd Outro)': { a: 'B', id: 'fkijihXrdhs', d: 79 },
  // The Fool
  'The Fool Intro': { a: 'B', id: 'MbuHfR4KreQ', d: 120 },
  "Let's Ride": { a: 'B', id: 'jF3U9EaVTNo', d: 146 },
  'Hotel Breakfast': { a: 'B', id: 'dCxDI5wI10Q', d: 131 },
  'I Think…': { a: 'B', id: '_qFCxcpC9Pw', d: 192 },
  'Thee 9 Is Up': { a: 'B', id: '2pQ8HyuTwOg', d: 184 },
  desiree: { a: 'B', id: '73YKQkmtiDk', d: 144 },
  'I Want It That Way': { a: 'B', id: 'H9O4nNSk8OA', d: 123 },
  BBY: { a: 'B', id: 'en365uDl454', d: 121 },
  'Inspiration Comes': { a: 'B, T', id: '7S4pG1l-d4A', d: 177 },
  egobaby: { a: 'B', id: 'gan2BP5gMN4', d: 139 },
  Trendy: { a: 'B', id: '0J_OMT59ddo', d: 164 },
  'Search True': { a: 'B', id: 'b8Acy5-AR48', d: 157 },
  'Wett (Water2)': { a: 'B', id: 'OhsaxHjjybg', d: 138 },
  // COLD VISIONS
  'PARANOIA INTRO': { a: 'B', id: 'eUUxXPiQ9Gg', d: 72 },
  WODRAINER: { a: 'B', id: 'TMabPjJGduc', d: 154 },
  'YUNG SHERMAN': { a: 'B, Yung Sherman', id: 'GaWsgE2mCik', d: 133 },
  FLATLINE: { a: 'B', id: '0nKgqxDH7e4', d: 175 },
  'ONE SECOND': { a: 'B, Y', id: '5rj_j5ZqT00', d: 113 },
  'SAD MEAL': { a: 'B', id: 'Fzt2c3IWkhQ', d: 122 },
  'FUN FACT': { a: 'B, Y', id: 'Zw-A3Phv3zQ', d: 110 },
  'ONLY GOD IS MADE PERFECT': { a: 'B', id: '7mUpFmjc3eM', d: 110 },
  'DONT WANNA HANG OUT': { a: 'B', id: 'af1r2LpI1rI', d: 100 },
  'I DONT LIKE PEOPLE (WHITEARMOR INTERLUDE)': { a: 'B', id: 'vB0FobIXD7Q', d: 38 },
  'I DONT LIKE PEOPLE': { a: 'B', id: 'k9SHS-XbFbY', d: 161 },
  'END OF THE ROAD BOYZ': { a: 'B', id: 'drQg7YjHqrs', d: 136 },
  'D.O.A': { a: 'B', id: 'uK0JJRXGssc', d: 141 },
  'DONT DO DRUGZ': { a: 'B', id: 'C9BW2UuwuVw', d: 94 },
  'LOWS PARTLYY': { a: 'B', id: '9ZnMrrUNnJ8', d: 135 },
  'SO COLD INTERLUDE': { a: 'B', id: 'LBrhKa7KDO4', d: 98 },
  'MESSAGE TO MYSELF': { a: 'B', id: 'rjC9s-UKBTQ', d: 74 },
  'TERRIBLE EXCELLENCE': { a: 'B, Y', id: 'f3obrUOiKH0', d: 154 },
  'RED CROSS': { a: 'B', id: 'Cb0fzgK6XN8', d: 138 },
  'LUCKY LUKE': { a: 'B, T, Y', id: 'kNk-9t6tRug', d: 128 },
  'RIVER FLOWS IN YOU': { a: 'B', id: 'a-AB9R5YKZo', d: 105 },
  'KING NOTHINGG': { a: 'B', id: '66eiQkMLC2Q', d: 147 },
  'BAD 4 BUSINESS': { a: 'B', id: 'odiEinMDKZg', d: 103 },
  OTHERSIDE: { a: 'B, Sickboyrari', id: '_QV12_KGpQ0', d: 157 },
  NORMAL: { a: 'B', id: 'IjsapjhXmvw', d: 79 },
  'FLEXING & FINESSING': { a: 'B', id: '2CdAd2eTVNY', d: 185 },
  PM2: { a: 'B', id: 'WTMat28s13c', d: 129 },
  FALSE: { a: 'B', id: 'yMhv69vlSZs', d: 129 },
  'CANT END ON A LOSS': { a: 'B', id: '0Gswc_scmSE', d: 214 },
  'COLD VISIONS (OUTRO 2)': { a: 'B', id: 'FBwBapAVAB0', d: 214 },
  // Spiderr
  UNDERSTATEMENT: { a: 'B', id: 'QMTS9HpOYqI', d: 189 },
  "IT'S OK TO NOT BE OK": { a: 'B', id: 'd1-9Qgz9qzc', d: 78 },
  'I AM SLOWLY BUT SURELY LOSING HOPE': { a: 'B', id: '7xo3vU3Gu5M', d: 154 },
  'ICARUS 3REESTYLE': { a: 'B', id: 'WktCNqcBe9Q', d: 121 },
  NOTHINGG: { a: 'B, Wondha Mountain', id: 'CR_myyxut-o', d: 187 },
  'BLUE CRUSH ANGEL': { a: 'B', id: 'IjEKn60Utxw', d: 195 },
  'DiSASTER PRELUDE': { a: 'B, E', id: 'WYWkop8mi-w', d: 118 },
  HAHAH: { a: 'B', id: 'm3sIZGXloQM', d: 137 },
  'DRAIN STORY': { a: 'B', id: 'NGdiQm4wI2M', d: 112 },
  Velociraptor: { a: 'B', id: '5ZnM6CKCi8k', d: 139 },
  'DRESDEN ER': { a: 'B', id: 'tIgkxZ6V24g', d: 176 },
  "She's Always Dancing": { a: 'B', id: 'vFsb2GjhmhM', d: 109 },
  'URIEL OUTRO': { a: 'B', id: 'IvFzbaaK8eo', d: 172 },
  // Crest
  'The Flag is Raised': { a: 'B, E', id: 'smVU37xAhY8', d: 180 },
  '5 Star Crest (4 Vattenrum)': { a: 'B, E', id: '8309BPqllyg', d: 530 },
  'White Meadow': { a: 'B, E', id: 'WUatbsdnDYA', d: 210 },
  Faust: { a: 'B, E', id: 'DWhp7RiNaoE', d: 126 },
  Yeses: { a: 'B, E', id: 'Gtg6X9_Wgrc', d: 182 },
  'Desire Is A Trap': { a: 'B, E', id: 'vEHsM-uV_Ec', d: 171 },
  'Chaos Follows': { a: 'B, E', id: 'LTOd2O2Lo5w', d: 151 },
  'Girls Just Want To Have Fun': { a: 'B, E', id: 'EgIQQlIeOWM', d: 135 },
  'Heaven Sings': { a: 'B, E', id: '-ClB-cWYioQ', d: 172 },
  // Good Luck
  Intro: { a: 'B', id: 'haxkg4PD6cE', d: 152 },
  Rainbow: { a: 'B', id: 'aaj85-jjdfA', d: 211 },
  Sun: { a: 'B', id: 'aFQa7KMJFzA', d: 194 },
  God: { a: 'B', id: 'WbN7pWjIF-E', d: 149 },
  Drama: { a: 'B', id: '39UXbM2cbRI', d: 121 },
  You: { a: 'B', id: 'M1KmTVvH_Jk', d: 127 },
  'Into One': { a: 'B', id: 'WaH1NZbtAgw', d: 193 },
  Grace: { a: 'B', id: 'rx7dkL5bLjY', d: 131 },
  'Sun (Toxe Remix)': { a: 'B', id: '60hFmkVR8NM', d: 167 },
  'Rainbow (make it double Oklou Mix)': { a: 'B', id: 'hObIwoYnmSg', d: 241 },
  'God (Evian Christ Remix)': { a: 'B', id: 'B_1pEJRSPe0', d: 206 },
  'Grace (Salem Remix)': { a: 'B', id: 'qMuXiXtIKKE', d: 139 },
  Gates: { a: 'B', id: 'mL-JYyviI3Y', d: 283 },
  // 333
  "Don't Worry": { a: 'B', id: 'EdKFth5KP-s', d: 139 },
  'Innocent Of All Things': { a: 'B', id: 'XRGBdHJfqR8', d: 130 },
  'Swan Lake': { a: 'B', id: 'LMn5FfAG_Og', d: 178 },
  'Oh Well': { a: 'B', id: 'I5con-FPW3g', d: 149 },
  Finder: { a: 'B', id: 'GlV3UmSXBzg', d: 105 },
  'Keys to the city': { a: 'B', id: '6KYqz-4M78w', d: 148 },
  '100s': { a: 'B', id: '0LP6zklxO8w', d: 147 },
  'Only One': { a: 'B', id: 'OEMOncFZf6M', d: 150 },
  'Reality Surf': { a: 'B', id: 'xUAgawZAi5g', d: 124 },
  'Mean Girls': { a: 'B', id: 'l4MNnJilyVk', d: 147 },
  Valerie: { a: 'B', id: 'lbkkKw5gypk', d: 161 },
  'Wings In Motion': { a: 'B', id: 'rTcXsy0oJR8', d: 145 },
  'Noblest Strive': { a: 'B', id: 'yoF1oI4MLO8', d: 136 },
  'It Girl': { a: 'B', id: 'kvv-khIuId4', d: 137 },
  Exstasia: { a: 'B', id: 'V24JnCGN1XE', d: 142 },
  'Hero of my story 3style3': { a: 'B', id: 'NuwWTCrI1V0', d: 120 },
  // Exeter
  'MIRROR (HYMN) - INTRO': { a: 'B', id: 'jhQFJJ6gq8M', d: 101 },
  WONDERLAND: { a: 'B, E', id: '_VOaMtKHUc0', d: 126 },
  'MERRY-GO-ROUND': { a: 'B', id: 'jORq1N2ty20', d: 124 },
  'RAIN3OW STAR (LOVE IS ALL)': { a: 'B', id: '77Tg9oNyLvw', d: 135 },
  'EVERY MOMENT SPECIAL': { a: 'B', id: 'OIZt2PXl2Do', d: 100 },
  'DNA RAIN': { a: 'B', id: '58XtGswe2bg', d: 108 },
  'OPEN SYMBOLS (PLAY) BE IN YOUR MIND': { a: 'B', id: 'nJelnXf6x0E', d: 128 },
  LOVESTORY: { a: 'B, E', id: 'zIGjcWNbJjY', d: 136 },
  IMAGINARY: { a: 'B', id: 'u1m4rpBMcwE', d: 127 },
  // Psykos
  Coda: { a: 'B, Y', id: '3ezcWZ0KkmU', d: 156 },
  Ghosts: { a: 'B, Y', id: 'yxPyqCBRReU', d: 181 },
  'Golden God': { a: 'B, Y', id: 'OKV0M2lEm-s', d: 140 },
  Still: { a: 'B, Y', id: 'dWJttnPOVb4', d: 218 },
  'Sold Out': { a: 'B, Y', id: 'fwEldo201ys', d: 137 },
  'Hanging From The Bridge': { a: 'B, Y', id: '6swWlLQFD6c', d: 188 },
  Enemy: { a: 'B, Y', id: 'FKpFLnFv1ew', d: 171 },
  'Things Happen': { a: 'B, Y', id: 'an_gnfu2Sfw', d: 166 },
  // Trash Island
  'You Lose': { a: 'E, B, T', id: 'yna1mRC6XEY', d: 158 },
  '30th Floor': { a: 'T, B', id: 'jGB5TDa-0mI', d: 130 },
  'Western Union': { a: 'E, T, B', id: 'CoEfQSoXodY', d: 120 },
  'The Void': { a: 'B, E, T', id: 'WVDqTXJByUM', d: 212 },
  Victim: { a: 'B, T, E', id: 'HDajKZ3ytdY', d: 154 },
  Waterfall: { a: 'T, B, E', id: '6THlyqDtC2U', d: 215 },
  '1:1': { a: 'E, T, Y', id: '2FVzhzfu2fM', d: 197 },
  'Acid Rain': { a: 'B, E', id: '1WSTFlDZ0Rk', d: 145 },
  // Red Light
  '1D': { a: 'B', id: 'J5Hik1ziLX8', d: 163 },
  'Golden Boy': { a: 'B', id: 'CNKXO3N5aF4', d: 163 },
  Westfield: { a: 'B', id: 'CbUEZFgCEiY', d: 156 },
  'Fake News': { a: 'B', id: 'bOrNrqms21g', d: 160 },
  'Steve Jobs': { a: 'B', id: 'DfCniCn_hdQ', d: 150 },
  Obedient: { a: 'B, E', id: 'eQpQtg0JE-8', d: 180 },
  'For You': { a: 'B, E', id: 'TU30hScNpww', d: 157 },
  Hex: { a: 'B', id: 'nZFLMsfpPnM', d: 157 },
  'That Thing You Do': { a: 'B, Uli K', id: 'Mo8VpWSfOU0', d: 175 },
  'Nike Just Do It': { a: 'B', id: 'sFhRM6sG7xQ', d: 243 },
  Decay: { a: 'B', id: 'k2PUV3KwIgY', d: 131 },
  'College Boy': { a: 'B', id: 'JEVohob5Wxg', d: 183 },
  Puppetmaster: { a: 'B', id: 'dqSHP0Bvzek', d: 162 },
  "I'm Goofy": { a: 'B', id: 'tT1KsSnWBhM', d: 193 },
  // Working On Dying
  'Redlight Moments': { a: 'B', id: '7vrg7i0zsW8', d: 190 },
  Lordship: { a: 'B, Y', id: 'AOx0rjiCSuM', d: 150 },
  Knightsbridge: { a: 'B', id: 'V0_-p4uH8sw', d: 120 },
  'Backstr€€t Boys': { a: 'B', id: 'xn5axac6MYA', d: 145 },
  'Under Your Spell': { a: 'B', id: 'YaVgaq774Os', d: 105 },
  'D-925': { a: 'B', id: '5wdXfoKPZF0', d: 156 },
  Gatekeeper: { a: 'B', id: 'q38I_ivrCbA', d: 197 },
  'Cherry Bracelets': { a: 'B', id: 'QduwdrxQPfo', d: 179 },
  'Best Buy': { a: 'B', id: 'sNEjKA7pDEM', d: 117 },
  // D&G
  'No Life Left': { a: 'B', id: 'UJmSicpMu2c', d: 154 },
  'Black Boy': { a: 'E', id: 'DHUG8M--CwQ', d: 139 },
  'First Crush': { a: 'B, E, Y', id: 'fsf7VmI943s', d: 192 },
  'Numb/Beverly Hills': { a: 'B', id: 'fFOctcWCJ-s', d: 134 },
  Cinderella: { a: 'B, E', id: '75pNJQQ13Pc', d: 203 },
  Wrong: { a: 'T', id: 'GCAQLuze-Gs', d: 178 },
  "Can't Trust": { a: 'T, Y', id: 'xPDXvZe8-Dk', d: 281 },
  'Wickr Man': { a: 'B', id: '39W8InPfYBU', d: 146 },
  'GT-R': { a: 'E', id: 'raLQWq_PRIE', d: 177 },
  Suffocation: { a: 'B', id: '5KDEwO20UVs', d: 152 },
  'Dumpster Baby': { a: 'B', id: 'xlqCMvyS8Es', d: 163 },
  Nosebleed: { a: 'T, B', id: 'X3eI7oFtETo', d: 205 },
  Scarecrows: { a: 'B', id: 'ks7VF4gfuz4', d: 157 },
  'Botox Lips': { a: 'B', id: 'QTgfmIuCpwA', d: 159 },
  Stalker: { a: 'B, E', id: 'oBw21Y-Q-Uk', d: 212 },
  'Happily Ever After': { a: 'E', id: 'htPhJeU6dZ4', d: 149 },
  Climbing: { a: 'T', id: 'N2UY_FWM48E', d: 196 },
  // AVP
  'Still in Search of Sunshine': { a: 'B, T', id: 'uTPSoxqtnP0', d: 171 },
  Painkillers: { a: 'B, T', id: 'pb8sBBV-le0', d: 176 },
  '1million': { a: 'B, T', id: 'w-gKWH5YddI', d: 155 },
  Brokeboy: { a: 'B, T, E', id: 'OKYUpvy7rzs', d: 166 },
  'Area 51': { a: 'B, T', id: '1omW9JR4tTI', d: 205 },
  '2X': { a: 'B, T', id: 'DDaL7KBjkDI', d: 138 },
  Winter: { a: 'B, T', id: 'Zacv0k1OxDY', d: 186 },
  // Sulfur Surfer
  'Sulfur Surfer': { a: 'B', id: 'eqXVOIDMvC0', d: 208 },
  'Versailles Flow': { a: 'B', id: '-diYiitISLQ', d: 218 },
  'Highland Tyrant': { a: 'B', id: '-Hxrx5uR568', d: 175 },
  'Dolor': { a: 'B', id: 'qHwsKedTFqo', d: 188 },
  'Killswitch': { a: 'B', id: 'vjcttn7ug4o', d: 163 },
  'Fox & Birch': { a: 'B, Current 93', id: 'mhREscMSS58', d: 256 },
  'Under my Umbrella': { a: 'B', id: 'nKMy03dttqY', d: 187 },
  'The Dark Mirror': { a: 'B', id: 'ytSIi_92Fzo', d: 251 },
  'Durins Bane': { a: 'B', id: 'tKqRDTVUhBQ', d: 184 },
  'Stoner': { a: 'B', id: '949W0iXwsug', d: 200 },
  'Black Fire': { a: 'B', id: '2Irtjbjhneo', d: 218 },
  'Blondie': { a: 'B', id: 'tLMFLiazkrA', d: 189 },
  'Scab': { a: 'B', id: 'lG7aPJgCTR0', d: 366 },
} as Record<string, { a: string; id: string; d: number }>
